build a program and deploy it on windows machine, accessible via a public IP:
  - pip install Flask
  - create a file called app.py
  - run the program: python app.py
  - Find your public IP:
      - use a service like ipify or just search "what is my ip" on google
      - fail because of proxy
  - Configure your router to forward port 5000 to your local machine:
      - fail because of password
  - Test your application


